### ISSUE TITLE
Error: Invalid URI "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"

### ISSUE THREAD

**Issue by PuKoren** [Automattic/juice#105]
With juiceRessources
Looks like juice trigger error when using //

And this link href is inside a

**Comment by Andersos** [comment]
Could you provide the code that makes the error or a simple example. Maybe even include the complete error message?

**Comment by PuKoren** [comment]
It look likes URL begining with // are seen as bad formed

This makes the loading fail
```html
<html>
<head>
    <link rel="stylesheet" href="//domain/stylesheet.css"/>
</head>
<body>
</body>
</html>
```

Error is just: [Error: Invalid URI "//gmpg.org/xfn/11"]

**Comment by jrit** [comment]
That style of URL normally would use the protocol, (http or https) that the page it is loaded in uses. Because juice and web-resource-inliner do not run in a page that has any concept of what protocol it is loaded with I'm considering updating web-resource-inliner to default to using https in these cases. That seems like the better option than http, assuming it is documented that if you want to load with http instead of https then you'd be required to use the protocol in the href or src. Since any domain could have different requirements, we can't create any option that would be particularly reliable to avoid the issue.

**Comment by parshap** [comment]
@jrit https as a default is probably a good idea. You can also go off of the `relativeTo` option if that's given.
