### ISSUE TITLE
Document "webResources"

### ISSUE THREAD

**Issue by GeoffreyPlitt** [Automattic/juice#117]
From the README, I can't figure out what to pass for "webResources", or really how to use remote resources at all. Is it recommended to just use https://www.npmjs.com/package/juice2 instead?

**Comment by jrit** [comment]
I will update the docs so that in the bullet about options (below) there is a link to https://www.npmjs.com/package/web-resource-inliner

webResources - An options object that will be passed through to web-resource-inliner for juice functions that will get remote resources (juiceResources and juiceFile). Defaults to {}.

**Comment by francoisromain** [comment]
I went to see the tests for web-resource-inliner, but I still don't understand what to passe to webResources to provide an url for an external file. Could you please provide an example?

**Comment by YuHuaiChen** [comment]
@francoisromain 
Hope this little example can help you : )

```javascript
var options = {
  preserveMediaQueries: true,
  // this is passed to the web-resource-inliner package
  // docs are in https://www.npmjs.com/package/web-resource-inliner
  webResources: { 
    scripts: false,    // don't fetch external scripts
    images: 500     // inline images with size smaller than this (kb)
  }
};
juice.juiceResources(htmlString, options, callback);
```
