### ISSUE TITLE
CSS to hide/show on focus

### ISSUE THREAD

**Issue by donniev** [Automattic/juice#143]
```
.span3:focus ~ .alert {
  display: none;
}
.span2:focus ~ .alert {
  display: block;
}
```

Juice does not seem to handle this behavior. Is that a known issue?

**Comment by jrit** [comment]
When you say it doesn't handle the behavior, do you mean that you expect this would be inlined or that the CSS would be preserved in a `<style>` tag so that this would be applied when the `focus` occurs?

**Comment by Amerr** [comment]
It should be preserved in style tag and also other pseudo selectors like **:hover :active** . is these styles are ignore by juice? . The document specifies 
** juice.ignoredPseudos**
Array of ignored pseudo-selectors such as 'hover' and 'active'

If not how to implement it in provided options ?

**Comment by jrit** [comment]
I have always used a wrapper like `@media all {...}` around what isn't being inlined. This is similar to the weirdness with preserving @font-face referenced in #132. We should probably rethink the way these are handled a bit since in neither case should the wrappers be needed. I should mention though that with inlining, you will always need `!important` on any pseudo classes, or they will never override the inline styles. Further, if inlining for emails, Yahoo will (currently) ignore all the styles unless they are prefixed with something like `body[style]`. Mainly just pointing these out for anyone who happens on this issue looking to solve their problem, not for the sake of the code needed for this issue.

**Comment by hellocosmin** [comment]
#314 adds an option that, when set to `true`, will properly preserve any pseudo selectors in your style tag.
