### ISSUE TITLE
inlining height

### ISSUE THREAD

**Issue by dantman** [Automattic/juice#167]
I'd like to inline height attributes the same way as width attributes. At least on `<img>` elements.

I'm fine writing it (I'm working on the PR now).

But is there any reason juice doesn't already do this or reason people may not want height inlined?

ie: Something I'll have to consider when implementing the defaults.

**Comment by jrit** [comment]
In most of my experience I was building for designs that had a specified width and would leave the heights unset so they were `auto` based on the widths. So, that was just the bias I had when I added the feature.

If you are adding an option `applyHeightAttributes` and have the default `false` then it shouldn't cause anyone any trouble. You likely want to use the same or similar list of elements to apply to as for width., though add another variable for the list rather than using the same one as for the width attributes.
