### ISSUE TITLE
Update readme to include installation instructions for bower and npm

### ISSUE THREAD

**Issue by jfyzhao** [Automattic/juice#253]
It would be nice to update the readme to include installation instructions for bower (bower install juicecss) and npm (npm install juice).

Happy to push up a fix if given access.

**Comment by jrit** [comment]
I didn't realize juice was listed as a package on bower. There isn't any .bowerrc in the repo and also no client-packaged file included, so I don't think it would be appropriate to advertise that this is an official bower compatible repo, since it isn't at the moment. Seems reasonable to add npm instructions though.

**Comment by jfyzhao** [comment]
Awesome - I can go ahead and make that change but it looks like I don't have push access.

**Comment by jrit** [comment]
I will be able to merge a PR for you
