### ISSUE TITLE
Juice hangs when unbalanced curly brackets in content.

### ISSUE THREAD

**Issue by jpirkey** [Automattic/juice#260]
So the juice cli is hanging in a very specific scenario.  I have narrowed it down to unbalanced curly brackets in the content.  Adding the second `}` to `{{father_of_child.name}` resolves the issue.

This has been confirmed on node versions `v7.7.1` and `v6.8.1` on Amazon Linux and MacOS 10.12.3

### Command line call to juice
```
node ./node_modules/.bin/juice --insert-preserved-extra-css true --apply-style-tags true --preserve-media-queries true --preserve-font-faces true /tmp/html_inlinify_src_v19FAi /tmp/html_inlinify_out_5qsE17
```

### Contents of `/tmp/html_inlinify_src_v19FAi`:
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<body bgcolor="#FFFFFF">
  <div id="Email">
    <table class="body-wrap"><tbody><tr><td>
    	</td>
    	<td class="container">
    		<div class="content">
          <div class="content-level-2">
            <h3 style="text-align:center;"><strong>Jane Smith</strong></h3>
            <h2 style="text-align:center;">Standard Agreement</h2>
            <div style="text-align:center;">Between <br><br>Jack Jones &amp; {{father_of_child.name}<span></span></div>
            <div style="text-align:center;">and</div>
            <div style="text-align:center;">Jane Smith</div>
            <div style="text-align:center;">
              <h2>DEPOSIT</h2>
              Non refundable or transferable deposit <strong>of $179</strong> TO BE PAID TO CONFIRM
            </div>
          </div>
        </div>
    	</td>
    </tr></tbody></table>
  </div>
</body>
</html>
```

**Comment by ziemkowski** [comment]
I can reproduce this with a far more minimal test case:

### Command line call to juice

`juice in.html out.html`

### Contents of `in.html`:
```html
<html>
  <body>
    <div>
      <div>
        <div>
          <div>
            {{
          </div>
        </div>
      </div>
    </div>
  </body>
</html>
```

Changing the div spacing, the element depth, or double braces all cause it to work as expected.

**Comment by ziemkowski** [comment]
Here it is on RunKit:

https://runkit.com/ziemkowski/juice-issue-260

Change any of it and it'll return HTML.

**Comment by ziemkowski** [comment]
@jrit  this issue is due to the new code blocks [regex for Handlebars](https://github.com/Automattic/juice/commit/280c311f24e05b21f8e7a47c926eead1f2d06a4f#diff-b967d865ca305d4506093665ba1d28fdR68) added in 4.0.

The node profiler reports this after processing `in.html` from my prior comment:
```
[JavaScript]:
   ticks  total  nonlib   name
   67196  99.5%   99.5%   RegExp: {{((.|\\s)*?)}}
```

I'm assuming it's a regex [catastrophic backtracking](http://www.regular-expressions.info/catastrophic.html) bug and that the `'((.|\\s)*?)'` string constant in `lib/cheerio.js` probably needs to be reworked to something more simplistic, such as just `'(.*?)'` now that it is being used for more formats. I imagine it would be beneficial move that inner regex to the codeBlock definition too since various blocks may have different rules for acceptable inner content.

### Workaround

This regression can be avoided by removing the Handlebars codeblock prior to calling `juice()`:

```js
delete juice.codeBlocks.HBS
```

**Comment by alavers** [comment]
@ziemkowski @jrit This is a pretty severe issue as it is a potential DoS attack vector.

I stumbled upon it via https://github.com/niftylettuce/email-templates. If you're rendering an EJS email template with an unescaped tag `<%- %>` then the string `<%` in user input can lock up your node process.
