### ISSUE TITLE
Bump web-resource-inliner to v4.1.0 to remove need for eval

### ISSUE THREAD

**Issue by marcusmateus** [Automattic/juice#266]
Hi,

The version of web-resource-inliner currently used by juice requires a version of DataUri that needs the evil `eval` available, but that has since been fixed: jrit/web-resource-inliner#26...

Our environment has `eval` disabled due to security concerns... and thus we can't use juice.  Bumping the version of web-resource-inliner would make it a non-issue.

Thanks!

**Comment by jrit** [comment]
Hi @marcusmateus 
I'm a little confused by your issue, the package.json in juice@4 has web-resource-inliner at ^4.0.0 which should install 4.1.0 already. I'm going to publish a new version of juice shortly since there was some outstanding changes and will bump the dependency, but you may have a different issue.
