### ISSUE TITLE
Broken encoding since v9.0.0

### ISSUE THREAD

**Issue by ligiaandreica** [Automattic/juice#493]
Hi! 👋  I've noticed a change in how `juice` deals with encoding after upgrading from v8.1.0 to v9.0.0.

Running the following command containing `'`

```
juice(
      `<body>
        <p>Hi, we&#x27;re testing!</p>
      </body>`,
    )
```
 gives the following results:

### v8.1.0
```
<body>
        <p>Hi, we&#x27;re testing!</p>
</body>
```
<img width="176" alt="image" src="https://github.com/user-attachments/assets/0bd649d4-b04f-48b2-8cf6-6f7d5121b570">

### v9.0.0 - changes `&` char to `&amp;` breaking the UI.
```
<body>
        <p>Hi, we&amp;#x27;re testing!</p>
</body>
```
<img width="215" alt="image" src="https://github.com/user-attachments/assets/d3cf805b-d061-40c9-94ac-320cec854fc2">

**Comment by AngeloChecked** [comment]
Hi @ligiaandreica! 

@Gafreax and I ran into the same issue you did, which is connected to this commit: https://github.com/cheeriojs/cheerio/commit/50b5d5ce49f7863ed70c82dad2652bc8cb147859. While the patch is allowed as a peer dependency, it introduced a bug: https://github.com/Automattic/juice/blob/master/package.json#L38.

One possible solution is to force the peer dependency to use the RC version in the `package.json`:

```json
	"overrides": {
		"cheerio": "^1.0.0-rc.12"
	},
```

bye!

**Comment by cossssmin** [comment]
Will have to check the encoding issue in particular (parser options are now passed under an `xml` key to cheerio, but indeed cheerio unexpectedly [released a bunch of breaking changes from a Release Candidate](https://github.com/cheeriojs/cheerio/releases/tag/v1.0.0).

We should probably pin Juice 10.x to use `cheerio@1.0.0-rc.12` otherwise v1.0.0 gets installed.

**Comment by jrit** [comment]
10.0.1 is released :)
